### ISSUE TITLE
last() failes while quoting integer

### ISSUE THREAD

**Issue by axelhahn** [catfan/Medoo#1011]
**Information**
- Version of Medoo: 2.1.2
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System (Liunx\Windows\Mac): Win

**Describe the Problem**
After migrating from 1.x to 2.1,2 the method last() does not work (in my app) anymore. It occurs on PHP 7.4 and 8.0.

**Detail Code**
after an insert I use `echo $oDB->last();`

```PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Medoo\Medoo::quote() must be of the type string, float given, called in PATH\medoo\src\Medoo.php on line 607 and defined in PATH\medoo\src\Medoo.php:696
Stack trace:
#0 PATH\medoo\src\Medoo.php(607): Medoo\Medoo->quote(33427)
#1 PATH\medoo\src\Medoo.php(2190): Medoo\Medoo->generate('INSERT INTO `pa...', Array)
#2 PATH\classes\crawler-base.class.php(855): Medoo\Medoo->last()
```
In #0 the problem is shown: the quote() method got an integer called in generate(). 
In the source of generate() the value PDO::PARAM_STR seems to catch integer values. In generate the integer values must be handled before a string - or the qote() method must detect an integer.
My fast fix was adding a test `is_integer($value[1])` in the generate() method before handling strings.
```
protected function generate(string $statement, array $map): string
{
...
        foreach ($map as $key => $value) {
            // Fast fix: adding is_integer()
            if (is_integer($value[1])) {
                $replace = $value[0] . '';
            } elseif ($value[1] === PDO::PARAM_STR) {
                $replace = $this->quote($value[0]);
            } elseif ($value[1] === PDO::PARAM_NULL) {
                $replace = 'NULL';
            } elseif ($value[1] === PDO::PARAM_LOB) {
                $replace = '{LOB_DATA}';
            } else {
                $replace = $value[0] . '';
            }
```

**Expected output**
Get a string with last query.

**Comment by axelhahn** [comment]
added https://github.com/catfan/Medoo/pull/1020
