### ISSUE TITLE
Unable to execute a query from a remote server such as Planetscale

### ISSUE THREAD

**Issue by jcchikikomori** [catfan/Medoo#1044]
**Information**
- Version of Medoo: 2.1.4
- Version of PHP: 8.0
- Type of Database (MySQL, MSSQL, SQLite...): MySQL
- System: MacOS

**Describe the Problem**
Uncaught PDOException near either column name or FROM

**Detail Code**
The detail code you are using causes the problem.
```php
// Write your PHP code here
use Medoo\Medoo;

public function connect_database(): Medoo
{
        $database_properties = [
          'type' => $_ENV['DB_TYPE'] ?? 'mysql',
          'database' => $_ENV['DB_NAME'],
          'host' => $_ENV['DB_HOST'],
          'username' => $_ENV['DB_USER'],
          'password' => $_ENV['DB_PASS'],
          'charset' => $_ENV['DB_CHARSET'] ?? null,
          'port' => $_ENV['DB_PORT'] ?? null, // if defined then use, else default
          'option' => [
            PDO::ATTR_CASE => PDO::CASE_NATURAL,
            PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/cert.pem' // using planetscale as Database server
          ],
          'logging' => true,
        ];
        return new Medoo($database_properties);
}

var_dump($this->db_connection->debug()->select("user_types", "*")); die();
```

**Expected output**
Working query with var_dump()
```
array(2) { [0]=> array(3) { ["id"]=> int(0) ["user_type"]=> string(5) "admin" ["type_desc"]=> string(14) "Administrators" } [1]=> array(3) { ["id"]=> int(1) ["user_type"]=> string(4) "user" ["type_desc"]=> string(5) "Users" } }
```

**Notes**
Working in native implementation
```
use PDO;

$dsn = "mysql:host={$_ENV['DB_HOST']};dbname={$_ENV['DB_NAME']}";
$options = array(PDO::MYSQL_ATTR_SSL_CA => "/etc/ssl/cert.pem");
$pdo = new PDO($dsn, $_ENV["DB_USER"], $_ENV["DB_PASS"], $options);
$query = $pdo->prepare('SELECT * FROM `user_types`');
$query->execute();
$result = $query->fetchAll(PDO::FETCH_ASSOC);
var_dump($result); die();
```

**Comment by jcchikikomori** [comment]
Error Shown
```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1105 syntax error at position 49 near 'user_types' in /Users/redacted/www/hello-php/vendor/catfan/medoo/src/Medoo.php:563 Stack trace: #0 /Users/redacted/www/hello-php/vendor/catfan/medoo/src/Medoo.php(563): PDOStatement->execute() #1 /Users/redacted/www/hello-php/vendor/catfan/medoo/src/Medoo.php(1595): Medoo\Medoo->exec(Object(PDOStatement), Array) #2 /Users/redacted/www/hello-php/classes/Registration.php(95): Medoo\Medoo->select('user_types', Array) #3 /Users/redacted/www/hello-php/register.php(24): classes\Registration->getUserTypes() #4 {main} thrown in /Users/redacted/www/hello-php/vendor/catfan/medoo/src/Medoo.php on line 563
```

**Comment by chriscct7** [comment]
We're running into the same issue on PlanetScale.

The DB type is set to MySQL (hardcoded), and we don't use custom charsets, ports or ATTR cases.

When we run debug() and ask Medoo to output the SQL it thinks it should run, the SQL statement outputted is correct and runs fine if we execute it manually, but for some reason, that SQL statement is not the one Medoo is actually running.

We're able to replicate this with an extremely simple test case:

``` php
global $container;
$container['db'] = function () {
	return new Medoo(
		[
			'database_type' => 'mysql',
			'database_name' => DB_NAME,
			'server'        => DB_HOST,
			'username'      => DB_USER,
			'password'      => DB_PASSWORD,
			'option'        => array(
				\PDO::ATTR_ERRMODE       => \PDO::ERRMODE_EXCEPTION,
				\PDO::MYSQL_ATTR_SSL_CA   => dirname(__FILE__) . '/cacert.pem'
			)
		]
	);
};
$app = $container['db']->select( 'test_table',['id'], [ "LIMIT" => 1 ] );
```
where the test_table has 2 columns, an autoincrementing ID column and a VARCHAR value column

We also get a syntax error like the previous reporter. 

We've confirmed the DB variables are correctly set (though we wouldn't get the syntax error but rather a connection failed error if they weren't) and we did the same for the cacert.pem to ensure it's in the right place (and again it would also trigger a different error if it was in the wrong place).

Note, if it helps, PlanetScale offers a free db plan, and we're able to replicate this issue on that plan as well.

**Comment by chriscct7** [comment]
Notably, if I run
```
$app = $container['db']->query("SELECT `id` FROM `test_table` WHERE `id` = 1 LIMIT 1;")->fetchAll();
```

The result works with no error.

**Comment by chriscct7** [comment]
Ok, progress to report!

I have figured out that with the following modifications, the library starts working again on PlanetScale:

In the `tableQuote` function, changing it to return the column in a tick instead of in double quotes:
```
return '`' . $this->prefix . $table . '`';
                ```
                
and in the `columnQuote` function, doing the same:
```
return strpos($column, '.') !== false ?
                '`' . $this->prefix . str_replace('.', '"."', $column) . '`' :
                '`' . $column . '`';
                ```
This has to be related to the handling of the MySQL ANSI_QUOTES

**Comment by chriscct7** [comment]
Ok, so this seems to be done because of #578, where it discusses the use of double quotes instead of backticks to adhere to the SQL-92 standard

**Comment by chriscct7** [comment]
It looks like Vitess doesn't support alternative SQL_MODES. 

@catfan would it be okay if we submit a pr to allow for an option that would let PlanetScale (and similar MySQL compatible database types that don't support the changing of SQL_MODE) to use backticks instead of double quotes for these two cases?

Also, are there other places we need to account for the double quotes other than just the two places mentioned above if SQL_MODE can't be altered to ANSI_QUOTES?

**Comment by chriscct7** [comment]
Note, the lack of ANSI_QUOTES support is a known issue for Vitess: https://github.com/vitessio/vitess/issues/7769

**Comment by orware** [comment]
@catfan,

I've put together the associated [PR#1061](https://github.com/catfan/Medoo/pull/1061) above in case it might be considered as a potential solution for this, considering that the likelihood of `ANSI_QUOTES` support being added on the Vitess side in the near future is fairly slim and this would be a workable solution that shouldn't affect existing users, but would provide flexibility for PlanetScale users (or any other database that might need this workaround) to still make use of Medoo easily.

The usage is quite simple and after instantiating a new Medoo instance you would simply add a call to `setIdentifierDelimiter()` and pass in value you want to utilize instead of the default double quote value.

**Comment by chriscct7** [comment]
We've tested the PR orware submitted above and it works fantastically

**Comment by benjaminprojas** [comment]
Is there any progress on this? Would love to see https://github.com/catfan/Medoo/pull/1061 merged in.
