### ISSUE TITLE
Unable to count with condition. string(58) "preg_match() expects parameter 2 to be string, array given"

### ISSUE THREAD

**Issue by pluveto** [catfan/Medoo#915]
**Describe the bug**
```
string(58) "preg_match() expects parameter 2 to be string, array given"
string(1935) "#0 [internal function]: flight\Engine->handleError(2, 'preg_match() ex...', '/www/wwwroot/ap...', 564, Array)
#1 /www/wwwroot/api.mgm.incolore.net/vendor/catfan/medoo/src/Medoo.php(564): preg_match('/([a-zA-Z0-9_\\....', Array, NULL)
#2 /www/wwwroot/api.mgm.incolore.net/vendor/catfan/medoo/src/Medoo.php(556): Medoo\Medoo->dataImplode(Array, Array, ' OR')
#3 /www/wwwroot/api.mgm.incolore.net/vendor/catfan/medoo/src/Medoo.php(719): Medoo\Medoo->dataImplode(Array, Array, ' AND')
#4 /www/wwwroot/api.mgm.incolore.net/vendor/catfan/medoo/src/Medoo.php(1294): Medoo\Medoo->whereClause(Array, Array)
#5 /www/wwwroot/api.mgm.incolore.net/app/Service/DeviceConfig.php(61): Medoo\Medoo->update('device_config', Array, Array)
```

**Information**
- Version of Medoo: latest
- Type of Database (MySQL, MSSQL, SQLite...):MySQL
- System (Liunx\Windows\Mac):Windows

**Detail Code**
The detail code causes the problem.
```
$where = array (
  'AND' => 
  array (
    'OR' => 
    array (
      'id' => 
      array (
        0 => 1,
        1 => 2,
      ),
    ),
    'userId' => '1',
  ),
);
return count($ids) == Core::$db->count(self::table, ["id"], $where);

```

**Comment by catfan** [comment]
I cannot reproduce the problem. Are you sure using the latest version?

And you don't need to wrap the condition like this, just simply use an `AND` or an `OR`:

```php
$where = [
    'AND' => [
        'id' => [1, 2],
        'userId' => '1',
    ]
];
// WHERE (`id` IN (1, 2) AND `userId` = '1')

$where = [
    'OR' => [
        'id' => [1, 2],
        'userId' => '1',
    ]
];
// WHERE (`id` IN (1, 2) OR `userId` = '1')
```

**Comment by pluveto** [comment]
My version: "catfan/medoo": "^1.7",
And `composer update` is not updating medoo which means this should be the latest release.

It's strange that it works with `select` statement
```
Core::$db->select(self::table, ["id"], $where)
```
But it does not work with `count` statement

```
Core::$db->count(self::table, ["id"], $where)
```

Full code:
```
public static function isIdsValid($ids, $userId = null)
    {
        $where = [
            "AND" => [
                "OR" => [
                    "id" => $ids
                ]
            ]
        ];
        if ($userId) {
            $where["AND"]["userId"] = $userId;
        }
        return count($ids) == Core::$db->count(self::table, ["id"], $where);
    }
```

**Comment by catfan** [comment]
Medoo.php(564): preg_match('/([a-zA-Z0-9_\\....', Array, NULL)

The error row number is not match the latest version https://github.com/catfan/Medoo/blob/master/src/Medoo.php#L564

And there is no column parameter for the `count()` https://medoo.in/api/count

Just call `$db->count(self::table, $where);`

**Comment by pluveto** [comment]
Thank u. Cloning from git and overriding works.
